version: 2.1
description: # Dark Maze Game build config

jobs:
  build:
    working_directory: ~/temp
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm wee
          command: npm install
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Test
          command: npm test

orbs:
  alexa:
    jobs:
      install:
        steps:
          - install
      my_inline_job:
        parameters:
          greeting_name:
            description: # a helpful description
            type: string
            default: olleh
        executor: my_inline_executor
        steps:
          - my_inline_command:
              greeting_name: <<parameters.greeting_name>>
    commands:
      install:
        steps:
          - run: npm i -G ask-cli
          - run: ask -v
      my_inline_command:
        parameters:
          greeting_name:
            type: string
        steps:
          - run: echo "hello <<parameters.greeting_name>>, from the inline command"
    executors:
      my_inline_executor:
        parameters:
          version:
            type: string
            default: "2.4"
        docker:
          - image: circleci/ruby:<<parameters.version>>
      default:
        description: |
          Node 10 runtime environment
        docker:
          - image: circleci/node:<<parameters.node>>
        parameters:
          node:
            default: "10"
            type: string


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - alexa/my_inline_job:
          name: mybuild # best practice is to name each orb job
      - alexa/my_inline_job:
          name: mybuild2
          greeting_name: world
      - alexa/install:
          name: testing_Install_command_fo_ASK_CLI