version: 2.1
description: # Dark Maze Game build config

jobs:
  build:
    working_directory: ~/temp
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm wee
          command: npm install
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Test
          command: npm test

orbs:
  alexa: alexa/alexa@0.0.0


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - alexa/my_inline_job:
          name: mybuild # best practice is to name each orb job
      - alexa/my_inline_job:
          name: mybuild2
          greeting_name: world
      - alexa/install_job:
          name: testing_Install_command_fo_ASK_CLI