version: 2
jobs:
  build:
    working_directory: ~/temp
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm wee
          command: npm install
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master